import SwiftUI

// MARK: About this Code
/// This code was auto-generated by Quassum.
/// https://svg-to-swiftui.quassum.com/
struct BalanceFigure: Shape {
    func path(in rect: CGRect) -> Path {
        var path = Path()
        let width = rect.size.width
        let height = rect.size.height
        path
            .move(
                to: CGPoint(
                    x: 0.44755*width,
                    y: 0.18268*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.57314*width,
                    y: 0.09134*height
                ),
                control1: CGPoint(
                    x: 0.51647*width,
                    y: 0.18268*height
                ),
                control2: CGPoint(
                    x: 0.57314*width,
                    y: 0.14146*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.44755*width,
                    y: 0
                ),
                control1: CGPoint(
                    x: 0.57314*width,
                    y: 0.04122*height
                ),
                control2: CGPoint(
                    x: 0.51647*width,
                    y: 0
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.32196*width,
                    y: 0.09134*height
                ),
                control1: CGPoint(
                    x: 0.37863*width,
                    y: 0
                ),
                control2: CGPoint(
                    x: 0.32196*width,
                    y: 0.04122*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.44755*width,
                    y: 0.18268*height
                ),
                control1: CGPoint(
                    x: 0.32196*width,
                    y: 0.14146*height
                ),
                control2: CGPoint(
                    x: 0.37863*width,
                    y: 0.18268*height
                )
            )
        path
            .closeSubpath()
        path
            .move(
                to: CGPoint(
                    x: 0.05989*width,
                    y: 0.30733*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.24669*width,
                    y: 0.30733*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.26165*width,
                    y: 0.31887*height
                ),
                control1: CGPoint(
                    x: 0.25531*width,
                    y: 0.30733*height
                ),
                control2: CGPoint(
                    x: 0.26256*width,
                    y: 0.3126*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.24397*width,
                    y: 0.49528*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.3614*width,
                    y: 0.60872*height
                ),
                control1: CGPoint(
                    x: 0.23717*width,
                    y: 0.55859*height
                ),
                control2: CGPoint(
                    x: 0.28841*width,
                    y: 0.5975*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.60216*width,
                    y: 0.64532*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.65385*width,
                    y: 0.83261*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.72277*width,
                    y: 0.86658*height
                ),
                control1: CGPoint(
                    x: 0.6611*width,
                    y: 0.85834*height
                ),
                control2: CGPoint(
                    x: 0.69602*width,
                    y: 0.87021*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.76947*width,
                    y: 0.81547*height
                ),
                control1: CGPoint(
                    x: 0.75496*width,
                    y: 0.86196*height
                ),
                control2: CGPoint(
                    x: 0.77581*width,
                    y: 0.83888*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.71052*width,
                    y: 0.60047*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.66473*width,
                    y: 0.56618*height
                ),
                control1: CGPoint(
                    x: 0.70599*width,
                    y: 0.58365*height
                ),
                control2: CGPoint(
                    x: 0.68649*width,
                    y: 0.57145*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.47929*width,
                    y: 0.52397*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.49516*width,
                    y: 0.3614*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.52599*width,
                    y: 0.35184*height
                ),
                control1: CGPoint(
                    x: 0.49652*width,
                    y: 0.34854*height
                ),
                control2: CGPoint(
                    x: 0.51329*width,
                    y: 0.34393*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.6144*width,
                    y: 0.40493*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.65204*width,
                    y: 0.41482*height
                ),
                control1: CGPoint(
                    x: 0.62483*width,
                    y: 0.4112*height
                ),
                control2: CGPoint(
                    x: 0.63798*width,
                    y: 0.41482*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.91864*width,
                    y: 0.41482*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.97758*width,
                    y: 0.37196*height
                ),
                control1: CGPoint(
                    x: 0.95174*width,
                    y: 0.41482*height
                ),
                control2: CGPoint(
                    x: 0.97758*width,
                    y: 0.3957*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.91864*width,
                    y: 0.32942*height
                ),
                control1: CGPoint(
                    x: 0.97758*width,
                    y: 0.34821*height
                ),
                control2: CGPoint(
                    x: 0.95174*width,
                    y: 0.32942*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.67289*width,
                    y: 0.32942*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.54549*width,
                    y: 0.2516*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.43757*width,
                    y: 0.22126*height
                ),
                control1: CGPoint(
                    x: 0.51329*width,
                    y: 0.23214*height
                ),
                control2: CGPoint(
                    x: 0.48382*width,
                    y: 0.22126*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.13969*width,
                    y: 0.22126*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.20543*width,
                    y: 0.06133*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.16644*width,
                    y: 0.00758*height
                ),
                control1: CGPoint(
                    x: 0.21495*width,
                    y: 0.03825*height
                ),
                control2: CGPoint(
                    x: 0.19727*width,
                    y: 0.01451*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.09163*width,
                    y: 0.03693*height
                ),
                control1: CGPoint(
                    x: 0.1347*width,
                    y: 0.00099*height
                ),
                control2: CGPoint(
                    x: 0.1007*width,
                    y: 0.01385*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.00321*width,
                    y: 0.25193*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.05989*width,
                    y: 0.30733*height
                ),
                control1: CGPoint(
                    x: -0.00812*width,
                    y: 0.28029*height
                ),
                control2: CGPoint(
                    x: 0.01047*width,
                    y: 0.30733*height
                )
            )
        path
            .closeSubpath()
        path
            .move(
                to: CGPoint(
                    x: 0.30972*width,
                    y: 0.9932*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.38407*width,
                    y: 0.96418*height
                ),
                control1: CGPoint(
                    x: 0.33783*width,
                    y: 0.99914*height
                ),
                control2: CGPoint(
                    x: 0.37319*width,
                    y: 0.98991*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.47203*width,
                    y: 0.75084*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.47521*width,
                    y: 0.73204*height
                ),
                control1: CGPoint(
                    x: 0.4743*width,
                    y: 0.7449*height
                ),
                control2: CGPoint(
                    x: 0.47521*width,
                    y: 0.73864*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.47521*width,
                    y: 0.66609*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.35097*width,
                    y: 0.64697*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.34281*width,
                    y: 0.64565*height
                ),
                control1: CGPoint(
                    x: 0.34826*width,
                    y: 0.64631*height
                ),
                control2: CGPoint(
                    x: 0.34553*width,
                    y: 0.64631*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.35596*width,
                    y: 0.73204*height
                )
            )
        path
            .addLine(
                to: CGPoint(
                    x: 0.27027*width,
                    y: 0.93978*height
                )
            )
        path
            .addCurve(
                to: CGPoint(
                    x: 0.30972*width,
                    y: 0.9932*height
                ),
                control1: CGPoint(
                    x: 0.2612*width,
                    y: 0.96221*height
                ),
                control2: CGPoint(
                    x: 0.27888*width,
                    y: 0.98628*height
                )
            )
        path
            .closeSubpath()
        return path
    }
}
